[custom]
;不要随意改变关键字，否则会导致出错
;参考acl4SSR规则

;自动测速：支持
;微软分流：支持
;苹果分流：支持
;openai分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;规则集定义
ruleset=🎯 全球直连,https://raw.githubusercontent.com/bigtomato969/rule/refs/heads/main/Direct.list
ruleset=🌍 独立代理,https://raw.githubusercontent.com/bigtomato969/rule/refs/heads/main/Proxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=📢 FCM,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🍀 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🐬 OneDrive,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=Ⓜ️ 微软Bing,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=♻️ Speedtest,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL



;策略组定义
custom_proxy_group=🚀 节点选择`url-test`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌍 独立代理`select`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🐬 OneDrive`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🤖 OpenAI`select`[]REJECT`[]DIRECT`[]🇦🇺 澳洲节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=📢 FCM`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=👨🏿‍💻 GitHub`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🪟 Microsoft`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🍎 Apple`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=📲 Telegram`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=♻️ Speedtest`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=📹 YouTube`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🎥 Netflix`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🎵 TikTok`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🎞️ 国内媒体`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=📺 哔哩哔哩`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🌍 国外媒体`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=Ⓜ️ 微软Bing`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=Ⓜ️ 微软云盘`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=Ⓜ️ 微软服务`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🎯 全球直连`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区
custom_proxy_group=🐟 漏网之鱼`select`[]REJECT`[]DIRECT`[]🚀 节点选择`[]🛩️ 大节点`[]🛩️ 超速节点`[]🇦🇺 澳洲节点`[]🇭🇰 香港节点`[]tw 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]kr 韩国节点`[]🌐 其他地区

custom_proxy_group=🛩️ 大节点`url-test`(?=.*(Large|香港|台湾|日本|韩国|美国|澳大利亚|英国))^((?!(应急|Lil|Game|Super)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🛩️ 超速节点`url-test`(?=.*(Super|香港|台湾|日本|韩国|美国|澳大利亚|英国))^((?!(应急|Lil|Game|Large)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(香港))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=tw 台湾节点`url-test`(?=.*(台湾))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(?=.*(日本))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(?=.*(美国))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=kr 韩国节点`url-test`(?=.*(韩国))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇦🇺 澳洲节点`url-test`(?=.*(澳洲))^((?!(应急|Lil|Game)).)`https://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🌐 其他地区`url-test`(^(?!.*(香港|台湾|日本|韩国|美国|澳大利亚|英国)).*)`https://www.gstatic.com/generate_204`300,,50



;启用自定义规则集

enable_rule_generator=true
overwrite_original_rules=true

